### ISSUE TITLE
New fields

### ISSUE THREAD

**Issue by johnny-co** [mattdy/MMM-TeslaFi#10]
Good morning Matt,

I haven't coded in a long time and not real familiar with GitHub so if I'm screwing up your code let me know. I was going to add a few new fields that i think might be useful. I had not intended to fork off your master code unless you would rather i not affect yours.
Next field Ill create is BatteryEx
ChargeState = Disconnected, Connected, or Scheduled
eg.
Scheduled                      217 miles (90% / 90%)
Disconnected(red)           30 miles (10% / 90%)
or something to that effect.
Would you rather this fork off yours or will you be merging together into master?

**Comment by mattdy** [comment]
Not at all - I'm glad to take any additions, especially in the form of new fields where they're optional whether people use them or not. I was just a bit more hesitant about making sweeping changes that affect other peoples use cases.

All of the information you're trying to display there is already available in separate fields, any particular reason why you're looking to merge them together?

**Comment by johnny-co** [comment]
For me just space saving, my MM is getting pretty busy with Nest, sonos, screenlogic pool, calendars,TAF/METAR, weather, etc. Consolidating three fields of information into one row helps me not to have to compromise. I'm also thinking a Header2 field to put security information on the header (next to the display name) like Unlocked-red (I'm constantly leaving my phone in the car and left searching the house for it), Window Down-yellow, or leave blank (letting me know car is fully secure).

I'll stay clear of modifying the existing fields, i didnt consider not everyone would like my changes or how it would impact their MM.

Also just ordered OpenSprinkler, open source lawn sprinkler project. i want to take a shot a creating a MMM, I'll likely plagiarize yours as much as possible since OS and TeslaFi appear to be JSON calls.

**Comment by mattdy** [comment]
Thanks - I would prefer to leave the current fields in place unless there's a clear bug/improvement. If you do add any additional ones then feel free to submit a PR for them!
