### ISSUE TITLE
Module does not load on recent versions of MagicMirror

### ISSUE THREAD

**Issue by mattdy** [mattdy/MMM-TeslaFi#31]
As in #30 - on recent versions of MagicMirror core an error is shown every time MMM-TeslaFi attempts to refresh the DOM - "module tries to update the DOM without being displayed"

It appears that a recent version of the MagicMirror core has added `module.data` as a protected variable - MMM-TeslaFi currently uses this to hold the incoming data from TeslaFi.

Should be a simple fix of just renaming the variable

**Comment by strif** [comment]
installed with mmpm this works perfectly! thank you Matt!
