### ISSUE TITLE
Scheduled time 

### ISSUE THREAD

**Issue by rkon189** [mattdy/MMM-TeslaFi#34]
Based on issue 33, it now displays a scheduled time to start charging, but it is showing "Scheduled 53 years ago"

**Comment by mattdy** [comment]
Looks like I used the wrong function for converting from Unix time stamps - sorry!

This should be fixed in 127db1fe8e72027ef5dd022699cd344115884be7, can you please test & verify? There may still be an outstanding issue with timezone support, so I'll leave this issue open for now.

**Comment by rkon189** [comment]
Looks like it has fixed it. Thanks!
