### ISSUE TITLE
Unable to select visible items

### ISSUE THREAD

**Issue by Ove-Andre** [mattdy/MMM-TeslaFi#56]
I cannot figure out how to use the "items" to limit the visible data.
Where is "item" suppoest to be in the config file?

This setup is showing all available items:
    {
      module: "MMM-Tesla",
      position: "bottom_right",
      config: {
        source: {
          name: "tessie",
          apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          vin: "xxxxxxxxxxxxxxxx",
          item: ['battery','range-estimated','locked','odometer'],
          unitDistance: 'km'
              }
      }
      },

**Comment by mattdy** [comment]
Hi,

The `items` and `unitDistance` configuration options need to go under the root `config` item, you've got them under `source` at the moment. Please try the following and let me know how you get on:

```
{
  module: "MMM-Tesla",
  position: "bottom_right",
  config: {
    source: {
      name: "tessie",
      apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      vin: "xxxxxxxxxxxxxxxx"
    },
    items: ['battery','range-estimated','locked','odometer'],
    unitDistance: 'km'
  }
},
```

**Comment by Ove-Andre** [comment]
Thanks Matt,

It now works like a charm!

/oa
