### ISSUE TITLE
Stuck on loading 

### ISSUE THREAD

**Issue by rkon189** [mattdy/MMM-TeslaFi#64]
Module stays on loading… the past 2 days
I haven’t changed anything on my config and my TeslaFi token is still valid.

**Comment by mattdy** [comment]
Sorry to hear that, the module hasn't been updated recently, so there aren't any code changes that would have broken functionality. It may be a change to one of the data sources that has started causing issues, but the module on my mirror is currently working fine. 

Could you please restart the mirror, and provide the logs so I can investigate? Thanks

**Comment by rkon189** [comment]
I think it may actually be a TeslaFi issue.
When I load the api query page, it is completely blank or says null for
everything.
I submitted a request to them, I’ll let you know if that solves it.

**Comment by rkon189** [comment]
It was a TeslaFi issue. I changed my car name from having a "*" to "•" in the Tesla App. That character must have killed TeslaFi's API.
I changed it back and immediately started getting data from the TeslaFi API and my mirror started working again.

**Comment by mattdy** [comment]
Thanks for the update, I'll close this issue.
